name: Selenium TestNG CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    name: Selenium Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chrome, firefox]
        environment: [dev, staging]
      fail-fast: false  # Continue other tests if one fails
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to v4
      
    - name: Set up Java 21
      uses: actions/setup-java@v4  # Updated to v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: maven  # Built-in Maven caching
        
    - name: Install Chrome (latest stable)
      uses: browser-actions/setup-chrome@latest
      
    - name: Install Firefox
      uses: browser-actions/setup-firefox@latest
      
    - name: Display browser versions
      run: |
        google-chrome --version
        firefox --version
        
    - name: Run Selenium Tests
      env:
        DISPLAY: :99
      run: |
        # Start virtual display for headless GUI testing
        sudo Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        
        # Run tests with Maven profiles
        mvn clean test \
          -P${{ matrix.browser }},headless,${{ matrix.environment }} \
          -Dbrowser=${{ matrix.browser }}-headless \
          -Denvironment=${{ matrix.environment }} \
          -Dmaven.test.failure.ignore=false \
          -Dwebdriver.chrome.driver=/usr/bin/google-chrome \
          -Dwebdriver.gecko.driver=/usr/bin/firefox
          
    - name: Generate Test Report
      if: always()  # Generate report even if tests fail
      run: |
        echo "Test execution completed for ${{ matrix.browser }} on ${{ matrix.environment }}"
        
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-${{ matrix.browser }}-${{ matrix.environment }}
        path: |
          target/surefire-reports/
          target/extent-reports/
          target/screenshots/
        retention-days: 30
        
    - name: Upload Test Results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results (${{ matrix.browser }}-${{ matrix.environment }})
        path: target/surefire-reports/testng-results.xml
        reporter: java-junit
        fail-on-error: false

  # Notification job that runs after all tests complete
  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: test
    if: always()
    
    steps:
    - name: Test Results Summary
      run: |
        echo "Test execution completed across all browser-environment combinations"
        echo "Check individual job results for detailed information"